const gpu = [
  {
    name: 'NVIDIA GeForce RTX 4090',
    description: '32GB GDDR6X, 16384 CUDA Cores, 2520MHz Boost clock. The ultimate consumer GPU for 4K gaming and creative workloads with DLSS 3 and ray tracing.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=RTX+4090',
    currentPrice: 1799.99,
    originalPrice: 1999.99,
    store: 'Amazon',
    category: 'gpu',
    url: 'https://www.amazon.com/dp/B0CHXLKRPW',
    rating: 4.8,
    stock: 12,
  },
  {
    name: 'NVIDIA GeForce RTX 4080 Super',
    description: '16GB GDDR6X, 10240 CUDA Cores, 2550MHz Boost. Premium 4K gaming GPU with exceptional ray tracing performance and DLSS 3.5 support.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=RTX+4080+Super',
    currentPrice: 999.99,
    originalPrice: 1099.99,
    store: 'Best Buy',
    category: 'gpu',
    url: 'https://www.bestbuy.com/site/nvidia-geforce-rtx-4080-super',
    rating: 4.7,
    stock: 25,
  },
  {
    name: 'AMD Radeon RX 7900 XTX',
    description: '24GB GDDR6, 6144 Stream Processors, 2500MHz Boost. AMD flagship GPU delivering outstanding 4K rasterization performance and massive VRAM.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=RX+7900+XTX',
    currentPrice: 849.99,
    originalPrice: 999.99,
    store: 'Newegg',
    category: 'gpu',
    url: 'https://www.newegg.com/amd-radeon-rx-7900-xtx',
    rating: 4.6,
    stock: 18,
  },
  {
    name: 'NVIDIA GeForce RTX 4070 Ti Super',
    description: '16GB GDDR6X, 8448 CUDA Cores, 2610MHz Boost. High-end 1440p/4K gaming GPU with excellent ray tracing and DLSS 3 frame generation.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=RTX+4070+Ti+Super',
    currentPrice: 749.99,
    originalPrice: 799.99,
    store: 'Amazon',
    category: 'gpu',
    url: 'https://www.amazon.com/dp/B0CSK7LJ8P',
    rating: 4.7,
    stock: 30,
  },
  {
    name: 'AMD Radeon RX 7800 XT',
    description: '16GB GDDR6, 3840 Stream Processors, 2430MHz Boost. Excellent 1440p gaming graphics card with great price-to-performance ratio.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=RX+7800+XT',
    currentPrice: 479.99,
    originalPrice: 549.99,
    store: 'Micro Center',
    category: 'gpu',
    url: 'https://www.microcenter.com/product/amd-radeon-rx-7800-xt',
    rating: 4.5,
    stock: 22,
  },
  {
    name: 'NVIDIA GeForce RTX 4060',
    description: '8GB GDDR6, 3072 CUDA Cores, 2460MHz Boost. The go-to entry-level ray tracing GPU for smooth 1080p gaming with DLSS 3 support.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=RTX+4060',
    currentPrice: 279.99,
    originalPrice: 329.99,
    store: 'Best Buy',
    category: 'gpu',
    url: 'https://www.bestbuy.com/site/nvidia-geforce-rtx-4060',
    rating: 4.4,
    stock: 45,
  },
];

const keyboards = [
  {
    name: 'Logitech G Pro X TKL',
    description: 'Professional-grade tenkeyless mechanical keyboard with GX Blue/Brown/Red switches, LIGHTSYNC RGB, and ultra-portable design for competitive gaming.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Logitech+G+Pro+X',
    currentPrice: 179.99,
    originalPrice: 229.99,
    store: 'Amazon',
    category: 'keyboard',
    url: 'https://www.amazon.com/dp/B09H6ZQKJL',
    rating: 4.6,
    stock: 35,
  },
  {
    name: 'Razer BlackWidow V4 Pro',
    description: 'Full-size mechanical keyboard with Razer Green switches, command dial, media keys, plush leatherette wrist rest, and Chroma RGB lighting.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=BlackWidow+V4+Pro',
    currentPrice: 149.99,
    originalPrice: 189.99,
    store: 'Razer',
    category: 'keyboard',
    url: 'https://www.razer.com/gaming-keyboards/blackwidow-v4-pro',
    rating: 4.5,
    stock: 28,
  },
  {
    name: 'SteelSeries Apex Pro TKL',
    description: 'Worlds fastest mechanical keyboard with OmniPoint adjustable switches, OLED smart display, and aircraft-grade aluminum frame.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Apex+Pro+TKL',
    currentPrice: 189.99,
    originalPrice: 249.99,
    store: 'SteelSeries',
    category: 'keyboard',
    url: 'https://steelseries.com/gaming-keyboards/apex-pro-tkl',
    rating: 4.7,
    stock: 15,
  },
  {
    name: 'Corsair K70 RGB Pro',
    description: 'Premium mechanical gaming keyboard with CHERRY MX Speed switches, PBT double-shot keycaps, aluminum frame, and per-key RGB backlighting.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Corsair+K70+RGB',
    currentPrice: 129.99,
    originalPrice: 169.99,
    store: 'Best Buy',
    category: 'keyboard',
    url: 'https://www.bestbuy.com/site/corsair-k70-rgb-pro',
    rating: 4.6,
    stock: 40,
  },
  {
    name: 'HyperX Alloy Origins 65',
    description: 'Compact 65% mechanical keyboard with HyperX Aqua switches, PBT keycaps, detachable USB-C cable, and vibrant RGB lighting effects.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=HyperX+Alloy+65',
    currentPrice: 89.99,
    originalPrice: 109.99,
    store: 'Amazon',
    category: 'keyboard',
    url: 'https://www.amazon.com/dp/B09HPR4LZV',
    rating: 4.4,
    stock: 55,
  },
  {
    name: 'ASUS ROG Azoth',
    description: 'Wireless 75% mechanical keyboard with ROG NX switches, OLED display, tri-mode connectivity, gasket mount design, and pre-lubed switches.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=ROG+Azoth',
    currentPrice: 199.99,
    originalPrice: 249.99,
    store: 'Newegg',
    category: 'keyboard',
    url: 'https://www.newegg.com/asus-rog-azoth',
    rating: 4.7,
    stock: 10,
  },
];

const mice = [
  {
    name: 'Logitech G Pro X Superlight 2',
    description: 'Ultra-lightweight 60g wireless gaming mouse with HERO 2 sensor, LIGHTFORCE hybrid switches, and 95-hour battery life. The choice of esports pros.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Superlight+2',
    currentPrice: 129.99,
    originalPrice: 159.99,
    store: 'Amazon',
    category: 'mouse',
    url: 'https://www.amazon.com/dp/B0C8F8ZKL4',
    rating: 4.8,
    stock: 50,
  },
  {
    name: 'Razer DeathAdder V3 Pro',
    description: 'Ergonomic 63g wireless esports mouse with Focus Pro 30K sensor, optical switches, and 90-hour battery. Iconic shape refined for competitive play.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=DeathAdder+V3+Pro',
    currentPrice: 119.99,
    originalPrice: 149.99,
    store: 'Razer',
    category: 'mouse',
    url: 'https://www.razer.com/gaming-mice/deathadder-v3-pro',
    rating: 4.7,
    stock: 32,
  },
  {
    name: 'SteelSeries Aerox 5 Wireless',
    description: 'Ultra-light 66g honeycomb wireless mouse with TrueMove Air sensor, 9 programmable buttons, AquaBarrier water resistance, and 80-hour battery.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Aerox+5+Wireless',
    currentPrice: 99.99,
    originalPrice: 139.99,
    store: 'Best Buy',
    category: 'mouse',
    url: 'https://www.bestbuy.com/site/steelseries-aerox-5-wireless',
    rating: 4.5,
    stock: 20,
  },
  {
    name: 'Corsair Dark Core RGB Pro SE',
    description: 'Wireless FPS/MOBA gaming mouse with 18K DPI optical sensor, Qi wireless charging, customizable side grips, and nine programmable buttons.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Dark+Core+RGB+Pro',
    currentPrice: 79.99,
    originalPrice: 99.99,
    store: 'Amazon',
    category: 'mouse',
    url: 'https://www.amazon.com/dp/B07TYWQTYT',
    rating: 4.3,
    stock: 38,
  },
  {
    name: 'HyperX Pulsefire Haste 2',
    description: 'Ultra-light 53g honeycomb wireless mouse with HyperX 26K sensor, rated for 100M clicks, and 100-hour battery on a single charge.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Pulsefire+Haste+2',
    currentPrice: 49.99,
    originalPrice: 69.99,
    store: 'HyperX',
    category: 'mouse',
    url: 'https://hyperx.com/products/pulsefire-haste-2-wireless',
    rating: 4.4,
    stock: 60,
  },
  {
    name: 'ASUS ROG Keris Wireless AimPoint',
    description: '75g lightweight ergonomic gaming mouse with ROG AimPoint 36K sensor, tri-mode connectivity, ROG Micro Switches, and swappable top shell.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=ROG+Keris',
    currentPrice: 69.99,
    originalPrice: 89.99,
    store: 'Newegg',
    category: 'mouse',
    url: 'https://www.newegg.com/asus-rog-keris-wireless',
    rating: 4.5,
    stock: 25,
  },
];

const monitors = [
  {
    name: 'Samsung Odyssey G7 27"',
    description: '27-inch QHD 240Hz 1ms Curved Gaming Monitor with G-Sync Compatible, HDR600, and immersive 1000R curve for competitive gaming.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Odyssey+G7+27',
    currentPrice: 499.99,
    originalPrice: 699.99,
    store: 'Amazon',
    category: 'monitor',
    url: 'https://www.amazon.com/dp/B08FF3LXSY',
    rating: 4.6,
    stock: 15,
  },
  {
    name: 'LG 27GP850-B Ultragear 27"',
    description: '27-inch QHD Nano IPS 180Hz 1ms gaming monitor with DCI-P3 98%, G-Sync Compatible, and VESA DisplayHDR 400 certification.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=LG+27GP850-B',
    currentPrice: 379.99,
    originalPrice: 449.99,
    store: 'Best Buy',
    category: 'monitor',
    url: 'https://www.bestbuy.com/site/lg-ultragear-27-gp850-b',
    rating: 4.5,
    stock: 20,
  },
  {
    name: 'Dell S2722DGM 27"',
    description: '27-inch QHD 165Hz 2ms Curved VA Gaming Monitor with AMD FreeSync Premium, VESA compatible, and built-in gaming crosshair overlay.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Dell+S2722DGM',
    currentPrice: 279.99,
    originalPrice: 349.99,
    store: 'Dell',
    category: 'monitor',
    url: 'https://www.dell.com/en-us/shop/dell-s2722dgm-gaming-monitor',
    rating: 4.4,
    stock: 30,
  },
  {
    name: 'ASUS ROG Swift PG27AQDM 27"',
    description: '27-inch QHD 240Hz OLED gaming monitor with 0.03ms response time, G-Sync Compatible, and true HDR with infinite contrast ratio.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=ROG+Swift+OLED',
    currentPrice: 799.99,
    originalPrice: 999.99,
    store: 'Newegg',
    category: 'monitor',
    url: 'https://www.newegg.com/asus-rog-swift-pg27aqdm',
    rating: 4.8,
    stock: 8,
  },
  {
    name: 'Gigabyte M27Q 27"',
    description: '27-inch QHD 170Hz 1ms SS IPS gaming monitor with 92% DCI-P3, KVM built-in, FreeSync Premium, and HDR ready for vibrant gameplay.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Gigabyte+M27Q',
    currentPrice: 299.99,
    originalPrice: 369.99,
    store: 'Amazon',
    category: 'monitor',
    url: 'https://www.amazon.com/dp/B08S6J6N6X',
    rating: 4.5,
    stock: 22,
  },
  {
    name: 'MSI Optix MAG274QRF-QD 27"',
    description: '27-inch QHD 165Hz 1ms Rapid IPS gaming monitor with Quantum Dot color technology, 97% DCI-P3, and G-Sync Compatible.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=MSI+MAG274QRF',
    currentPrice: 329.99,
    originalPrice: 399.99,
    store: 'Micro Center',
    category: 'monitor',
    url: 'https://www.microcenter.com/product/msi-optix-mag274qrf-qd',
    rating: 4.6,
    stock: 17,
  },
];

const laptops = [
  {
    name: 'ASUS ROG Zephyrus G14',
    description: '14-inch QHD 165Hz gaming laptop with AMD Ryzen 9 7940HS, NVIDIA RTX 4070, 16GB DDR5, 1TB SSD, and ROG Nebula Display.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Zephyrus+G14',
    currentPrice: 1299.99,
    originalPrice: 1599.99,
    store: 'Best Buy',
    category: 'laptop',
    url: 'https://www.bestbuy.com/site/asus-rog-zephyrus-g14',
    rating: 4.7,
    stock: 10,
  },
  {
    name: 'Razer Blade 15',
    description: '15.6-inch QHD 240Hz gaming laptop with Intel i9-13900H, NVIDIA RTX 4070, 16GB DDR5, 1TB SSD, and CNC aluminum chassis.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Razer+Blade+15',
    currentPrice: 2199.99,
    originalPrice: 2599.99,
    store: 'Razer',
    category: 'laptop',
    url: 'https://www.razer.com/gaming-laptops/razer-blade-15',
    rating: 4.5,
    stock: 6,
  },
  {
    name: 'Lenovo Legion Pro 5',
    description: '16-inch QHD 240Hz gaming laptop with AMD Ryzen 7 7745HX, NVIDIA RTX 4070, 32GB DDR5, 1TB SSD, and ColdFront 5.0 thermal system.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Legion+Pro+5',
    currentPrice: 1499.99,
    originalPrice: 1799.99,
    store: 'Lenovo',
    category: 'laptop',
    url: 'https://www.lenovo.com/us/en/p/legion-pro-5-gen-8',
    rating: 4.6,
    stock: 14,
  },
  {
    name: 'ASUS TUF Gaming A15',
    description: '15.6-inch FHD 144Hz gaming laptop with AMD Ryzen 7 7735HS, NVIDIA RTX 4060, 16GB DDR5, 512GB SSD, and MIL-STD-810H durability.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=TUF+Gaming+A15',
    currentPrice: 999.99,
    originalPrice: 1199.99,
    store: 'Amazon',
    category: 'laptop',
    url: 'https://www.amazon.com/dp/B0BTZC44YR',
    rating: 4.4,
    stock: 25,
  },
  {
    name: 'Dell G16 7630',
    description: '16-inch QHD 165Hz gaming laptop with Intel i7-13650HX, NVIDIA RTX 4070, 16GB DDR5, 1TB SSD, and Alienware-inspired thermal design.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Dell+G16',
    currentPrice: 1149.99,
    originalPrice: 1399.99,
    store: 'Dell',
    category: 'laptop',
    url: 'https://www.dell.com/en-us/shop/dell-g16-7630-gaming-laptop',
    rating: 4.3,
    stock: 18,
  },
  {
    name: 'MSI Stealth 16 Studio',
    description: '16-inch 4K 120Hz OLED gaming laptop with Intel i9-13900H, NVIDIA RTX 4070, 32GB DDR5, 2TB SSD, and ultra-slim magnesium alloy design.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Stealth+16',
    currentPrice: 1799.99,
    originalPrice: 2099.99,
    store: 'Newegg',
    category: 'laptop',
    url: 'https://www.newegg.com/msi-stealth-16-studio',
    rating: 4.5,
    stock: 8,
  },
];

const mercadolibre = [
  {
    name: 'Tarjeta de Video MSI RTX 4060 Ventus 2X Black 8GB OC',
    description: 'Tarjeta de video MSI NVIDIA GeForce RTX 4060 Ventus 2X Black 8GB GDDR6, overclockeada de fábrica.',
    imageUrl: 'https://placehold.co/400x300/fff059/1a1a2e?text=RTX+4060+ML',
    currentPrice: 7499,
    originalPrice: 9499,
    store: 'MercadoLibre',
    category: 'gpu',
    url: 'https://www.mercadolibre.com.mx/msi-rtx-4060',
    rating: 4.5,
    stock: 15,
  },
  {
    name: 'Monitor Gamer Samsung Odyssey G3 27\" 165Hz',
    description: 'Monitor gamer Samsung Odyssey G3 de 27 pulgadas, 165Hz, 1ms, Full HD, FreeSync Premium.',
    imageUrl: 'https://placehold.co/400x300/fff059/1a1a2e?text=Odyssey+G3+ML',
    currentPrice: 4399,
    originalPrice: 5699,
    store: 'MercadoLibre',
    category: 'monitor',
    url: 'https://www.mercadolibre.com.mx/samsung-odyssey-g3',
    rating: 4.4,
    stock: 22,
  },
  {
    name: 'Teclado Mecánico Redragon Kumara K552 RGB',
    description: 'Teclado mecánico Redragon Kumara K552 RGB, switches Outemu Blue, 87 teclas, retroiluminado.',
    imageUrl: 'https://placehold.co/400x300/fff059/1a1a2e?text=Kumara+K552+ML',
    currentPrice: 799,
    originalPrice: 1099,
    store: 'MercadoLibre',
    category: 'keyboard',
    url: 'https://www.mercadolibre.com.mx/redragon-kumara-k552',
    rating: 4.6,
    stock: 40,
  },
  {
    name: 'Mouse Gamer Logitech G203 Lightsync RGB',
    description: 'Mouse gamer Logitech G203 Lightsync RGB, 8000 DPI, 6 botones programables, iluminación RGB.',
    imageUrl: 'https://placehold.co/400x300/fff059/1a1a2e?text=G203+ML',
    currentPrice: 449,
    originalPrice: 649,
    store: 'MercadoLibre',
    category: 'mouse',
    url: 'https://www.mercadolibre.com.mx/logitech-g203',
    rating: 4.5,
    stock: 55,
  },
  {
    name: 'Audífonos Gamer HyperX Cloud Stinger 2',
    description: 'Audífonos gamer HyperX Cloud Stinger 2, drivers 50mm, diadema ajustable, compatibles multi-plataforma.',
    imageUrl: 'https://placehold.co/400x300/fff059/1a1a2e?text=Cloud+Stinger+ML',
    currentPrice: 1099,
    originalPrice: 1499,
    store: 'MercadoLibre',
    category: 'component',
    url: 'https://www.mercadolibre.com.mx/hyperx-cloud-stinger-2',
    rating: 4.4,
    stock: 30,
  },
  {
    name: 'Laptop Gamer ASUS TUF Gaming F15 FX507',
    description: 'Laptop gamer ASUS TUF Gaming F15, Intel i5-12500H, RTX 3050, 8GB RAM, 512GB SSD, 15.6\" 144Hz.',
    imageUrl: 'https://placehold.co/400x300/fff059/1a1a2e?text=TUF+F15+ML',
    currentPrice: 15999,
    originalPrice: 19499,
    store: 'MercadoLibre',
    category: 'laptop',
    url: 'https://www.mercadolibre.com.mx/asus-tuf-f15',
    rating: 4.3,
    stock: 8,
  },
  {
    name: 'SSD Kingston NV2 1TB NVMe M.2',
    description: 'SSD Kingston NV2 1TB NVMe PCIe 4.0, lecturas hasta 3500MB/s, escrituras hasta 2800MB/s.',
    imageUrl: 'https://placehold.co/400x300/fff059/1a1a2e?text=NV2+1TB+ML',
    currentPrice: 1299,
    originalPrice: 1699,
    store: 'MercadoLibre',
    category: 'component',
    url: 'https://www.mercadolibre.com.mx/kingston-nv2-1tb',
    rating: 4.6,
    stock: 35,
  },
  {
    name: 'Procesador AMD Ryzen 5 5600X',
    description: 'Procesador AMD Ryzen 5 5600X, 6 núcleos 12 hilos, 4.6GHz boost, AM4, 35MB cache.',
    imageUrl: 'https://placehold.co/400x300/fff059/1a1a2e?text=Ryzen+5600X+ML',
    currentPrice: 2399,
    originalPrice: 3299,
    store: 'MercadoLibre',
    category: 'cpu',
    url: 'https://www.mercadolibre.com.mx/amd-ryzen-5-5600x',
    rating: 4.7,
    stock: 18,
  },
  {
    name: 'Memoria RAM Corsair Vengeance DDR4 16GB 3200MHz',
    description: 'Memoria RAM Corsair Vengeance LPX DDR4, 16GB (2x8GB), 3200MHz, CL16, disipador de aluminio.',
    imageUrl: 'https://placehold.co/400x300/fff059/1a1a2e?text=Vengeance+16GB+ML',
    currentPrice: 849,
    originalPrice: 1149,
    store: 'MercadoLibre',
    category: 'component',
    url: 'https://www.mercadolibre.com.mx/corsair-vengeance-16gb',
    rating: 4.5,
    stock: 42,
  },
  {
    name: 'Silla Gamer Cougar Armor One',
    description: 'Silla gamer Cougar Armor One, reclinable 180°, soporte lumbar, reposabrazos 3D, base reforzada.',
    imageUrl: 'https://placehold.co/400x300/fff059/1a1a2e?text=Armor+One+ML',
    currentPrice: 3999,
    originalPrice: 5499,
    store: 'MercadoLibre',
    category: 'component',
    url: 'https://www.mercadolibre.com.mx/cougar-armor-one',
    rating: 4.2,
    stock: 12,
  },
];

const consoles = [
  {
    name: 'Sony PlayStation 5 Slim',
    description: 'PS5 Slim with ultra-fast SSD, DualSense wireless controller, ray tracing support, and access to an incredible library of exclusive games.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=PS5+Slim',
    currentPrice: 449.99,
    originalPrice: 499.99,
    store: 'Amazon',
    category: 'console',
    url: 'https://www.amazon.com/dp/B0CL5KNB9M',
    rating: 4.8,
    stock: 40,
  },
  {
    name: 'Xbox Series X',
    description: 'Fastest most powerful Xbox ever with 12 TFLOPS, 1TB SSD, Quick Resume, backwards compatibility, and Xbox Game Pass ecosystem.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Xbox+Series+X',
    currentPrice: 479.99,
    originalPrice: 499.99,
    store: 'Best Buy',
    category: 'console',
    url: 'https://www.bestbuy.com/site/microsoft-xbox-series-x',
    rating: 4.7,
    stock: 35,
  },
  {
    name: 'Nintendo Switch OLED',
    description: 'Nintendo Switch OLED Model with vibrant 7-inch OLED screen, enhanced audio, wide adjustable stand, 64GB internal storage, and dock with LAN port.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Switch+OLED',
    currentPrice: 299.99,
    originalPrice: 349.99,
    store: 'GameStop',
    category: 'console',
    url: 'https://www.gamestop.com/nintendo-switch-oled',
    rating: 4.6,
    stock: 50,
  },
  {
    name: 'Valve Steam Deck OLED',
    description: 'Steam Deck OLED with 7.4-inch HDR OLED display, AMD APU, 512GB NVMe SSD, updated cooling, and 50% longer battery life for gaming on the go.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Steam+Deck+OLED',
    currentPrice: 549.99,
    originalPrice: 649.99,
    store: 'Steam',
    category: 'console',
    url: 'https://store.steampowered.com/steamdeck',
    rating: 4.8,
    stock: 20,
  },
  {
    name: 'ASUS ROG Ally X',
    description: 'Handheld gaming PC with AMD Z1 Extreme, 7-inch FHD 120Hz display, 24GB LPDDR5, 1TB SSD, and dual USB-C with Thunderbolt 4 support.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=ROG+Ally+X',
    currentPrice: 699.99,
    originalPrice: 799.99,
    store: 'Best Buy',
    category: 'console',
    url: 'https://www.bestbuy.com/site/asus-rog-ally-x',
    rating: 4.5,
    stock: 15,
  },
  {
    name: 'Nintendo Switch Lite',
    description: 'Compact lightweight Nintendo Switch dedicated to handheld play with built-in controls, 5.5-inch screen, and up to 7 hours of battery life.',
    imageUrl: 'https://placehold.co/400x300/1a1a2e/e94560?text=Switch+Lite',
    currentPrice: 179.99,
    originalPrice: 199.99,
    store: 'Walmart',
    category: 'console',
    url: 'https://www.walmart.com/ip/nintendo-switch-lite',
    rating: 4.4,
    stock: 65,
  },
];

const dellProducts = [
  {
    name: 'Dell Alienware AW2724DM 27" QHD 180Hz Gaming Monitor',
    description: '27-inch QHD 180Hz IPS gaming monitor with NVIDIA G-Sync Compatible, VESA DisplayHDR 400, and 99% sRGB.',
    imageUrl: 'https://placehold.co/400x300/007db8/ffffff?text=Alienware+AW2724DM',
    currentPrice: 349.99,
    originalPrice: 449.99,
    store: 'Dell',
    category: 'monitor',
    url: 'https://www.dell.com/en-us/shop/dell-aw2724dm-gaming-monitor',
    rating: 4.5,
    stock: 20,
  },
  {
    name: 'Dell Alienware m16 R2 Gaming Laptop',
    description: '16-inch QHD 240Hz gaming laptop with Intel Core Ultra 9, NVIDIA RTX 4070, 32GB DDR5, 1TB SSD.',
    imageUrl: 'https://placehold.co/400x300/007db8/ffffff?text=Alienware+m16',
    currentPrice: 1699.99,
    originalPrice: 1999.99,
    store: 'Dell',
    category: 'laptop',
    url: 'https://www.dell.com/en-us/shop/alienware-m16-r2-gaming-laptop',
    rating: 4.6,
    stock: 8,
  },
  {
    name: 'Dell G2724D 27" QHD 165Hz Gaming Monitor',
    description: '27-inch QHD 165Hz IPS gaming monitor with AMD FreeSync Premium, 99% sRGB, and built-in crosshair overlay.',
    imageUrl: 'https://placehold.co/400x300/007db8/ffffff?text=Dell+G2724D',
    currentPrice: 249.99,
    originalPrice: 319.99,
    store: 'Dell',
    category: 'monitor',
    url: 'https://www.dell.com/en-us/shop/dell-g2724d-gaming-monitor',
    rating: 4.4,
    stock: 25,
  },
  {
    name: 'Dell G15 5530 Gaming Laptop',
    description: '15.6-inch FHD 165Hz gaming laptop with Intel i7-13650HX, NVIDIA RTX 4060, 16GB DDR5, 512GB SSD.',
    imageUrl: 'https://placehold.co/400x300/007db8/ffffff?text=Dell+G15',
    currentPrice: 999.99,
    originalPrice: 1249.99,
    store: 'Dell',
    category: 'laptop',
    url: 'https://www.dell.com/en-us/shop/dell-g15-5530-gaming-laptop',
    rating: 4.3,
    stock: 15,
  },
  {
    name: 'Dell Alienware AW3225QF 32" 4K 240Hz QD-OLED Gaming Monitor',
    description: '32-inch 4K 240Hz QD-OLED curved gaming monitor with Dolby Vision, NVIDIA G-Sync, and 0.03ms response time.',
    imageUrl: 'https://placehold.co/400x300/007db8/ffffff?text=AW3225QF+OLED',
    currentPrice: 1099.99,
    originalPrice: 1299.99,
    store: 'Dell',
    category: 'monitor',
    url: 'https://www.dell.com/en-us/shop/alienware-aw3225qf-4k-oled',
    rating: 4.8,
    stock: 6,
  },
  {
    name: 'Dell Inspiron 16 Plus Gaming Laptop',
    description: '16-inch 2.5K gaming laptop with Intel i7-13620H, NVIDIA RTX 4050, 16GB DDR5, 512GB SSD.',
    imageUrl: 'https://placehold.co/400x300/007db8/ffffff?text=Inspiron+16',
    currentPrice: 849.99,
    originalPrice: 1049.99,
    store: 'Dell',
    category: 'laptop',
    url: 'https://www.dell.com/en-us/shop/dell-inspiron-16-plus-gaming',
    rating: 4.2,
    stock: 18,
  },
  {
    name: 'Dell Alienware Pro Wireless Gaming Mouse',
    description: 'Wireless gaming mouse with 30K DPI sensor, 80-hour battery, lightweight 68g design, and RGB lighting.',
    imageUrl: 'https://placehold.co/400x300/007db8/ffffff?text=Alienware+Mouse',
    currentPrice: 79.99,
    originalPrice: 99.99,
    store: 'Dell',
    category: 'mouse',
    url: 'https://www.dell.com/en-us/shop/alienware-pro-wireless-mouse',
    rating: 4.4,
    stock: 30,
  },
  {
    name: 'Dell Alienware Pro Wireless Gaming Keyboard',
    description: 'Wireless mechanical gaming keyboard with Alienware linear switches, per-key RGB, and 100-hour battery.',
    imageUrl: 'https://placehold.co/400x300/007db8/ffffff?text=Alienware+KB',
    currentPrice: 129.99,
    originalPrice: 159.99,
    store: 'Dell',
    category: 'keyboard',
    url: 'https://www.dell.com/en-us/shop/alienware-pro-wireless-keyboard',
    rating: 4.5,
    stock: 22,
  },
];

const microCenterProducts = [
  {
    name: 'NVIDIA GeForce RTX 4070 Super',
    description: '12GB GDDR6X, 7168 CUDA Cores, 2475MHz Boost. Excellent 1440p gaming GPU with DLSS 3 and ray tracing.',
    imageUrl: 'https://placehold.co/400x300/e63946/ffffff?text=RTX+4070+Super',
    currentPrice: 549.99,
    originalPrice: 599.99,
    store: 'Micro Center',
    category: 'gpu',
    url: 'https://www.microcenter.com/product/rtx-4070-super',
    rating: 4.7,
    stock: 15,
  },
  {
    name: 'AMD Ryzen 7 7800X3D',
    description: '8-core 16-thread gaming processor with 96MB 3D V-Cache, 4.2GHz base, 5.0GHz boost, AM5 socket.',
    imageUrl: 'https://placehold.co/400x300/e63946/ffffff?text=Ryzen+7800X3D',
    currentPrice: 339.99,
    originalPrice: 449.99,
    store: 'Micro Center',
    category: 'cpu',
    url: 'https://www.microcenter.com/product/amd-ryzen-7-7800x3d',
    rating: 4.9,
    stock: 10,
  },
  {
    name: 'Corsair Vengeance DDR5 32GB 6000MHz',
    description: '32GB (2x16GB) DDR5 6000MHz CL30 memory kit with Intel XMP 3.0, low-profile aluminum heat spreader.',
    imageUrl: 'https://placehold.co/400x300/e63946/ffffff?text=Vengeance+DDR5',
    currentPrice: 89.99,
    originalPrice: 119.99,
    store: 'Micro Center',
    category: 'component',
    url: 'https://www.microcenter.com/product/corsair-vengeance-ddr5-32gb',
    rating: 4.6,
    stock: 35,
  },
  {
    name: 'Samsung 990 Pro 2TB NVMe SSD',
    description: '2TB PCIe 4.0 NVMe M.2 SSD with 7450MB/s reads, 6900MB/s writes, and Samsung V-NAND TLC.',
    imageUrl: 'https://placehold.co/400x300/e63946/ffffff?text=990+Pro+2TB',
    currentPrice: 149.99,
    originalPrice: 199.99,
    store: 'Micro Center',
    category: 'component',
    url: 'https://www.microcenter.com/product/samsung-990-pro-2tb',
    rating: 4.8,
    stock: 28,
  },
  {
    name: 'ASUS ROG Strix B650E-E Gaming WiFi Motherboard',
    description: 'AM5 ATX motherboard with PCIe 5.0, DDR5, WiFi 6E, 2.5G LAN, and robust 14+2 power stages.',
    imageUrl: 'https://placehold.co/400x300/e63946/ffffff?text=ROG+Strix+B650E',
    currentPrice: 249.99,
    originalPrice: 309.99,
    store: 'Micro Center',
    category: 'component',
    url: 'https://www.microcenter.com/product/asus-rog-strix-b650e-e',
    rating: 4.5,
    stock: 12,
  },
  {
    name: 'Corsair RM850x 850W 80+ Gold PSU',
    description: '850W fully modular 80+ Gold power supply with zero RPM fan mode, 105°C capacitors, and 10-year warranty.',
    imageUrl: 'https://placehold.co/400x300/e63946/ffffff?text=RM850x',
    currentPrice: 109.99,
    originalPrice: 139.99,
    store: 'Micro Center',
    category: 'component',
    url: 'https://www.microcenter.com/product/corsair-rm850x-850w',
    rating: 4.7,
    stock: 20,
  },
  {
    name: 'NZXT H7 Flow RGB Mid-Tower Case',
    description: 'Mid-tower ATX case with perforated front panel, 3x RGB fans, tempered glass side panel, and cable management.',
    imageUrl: 'https://placehold.co/400x300/e63946/ffffff?text=NZXT+H7+Flow',
    currentPrice: 109.99,
    originalPrice: 139.99,
    store: 'Micro Center',
    category: 'component',
    url: 'https://www.microcenter.com/product/nzxt-h7-flow-rgb',
    rating: 4.5,
    stock: 18,
  },
  {
    name: 'SteelSeries Arctis Nova 7 Wireless Headset',
    description: 'Wireless gaming headset with 40mm drivers, 38-hour battery, ClearCast Gen 2 mic, and simultaneous Bluetooth.',
    imageUrl: 'https://placehold.co/400x300/e63946/ffffff?text=Arctis+Nova+7',
    currentPrice: 149.99,
    originalPrice: 179.99,
    store: 'Micro Center',
    category: 'headset',
    url: 'https://www.microcenter.com/product/steelseries-arctis-nova-7',
    rating: 4.6,
    stock: 22,
  },
  {
    name: 'Logitech G Pro X Superlight 2',
    description: 'Ultra-lightweight 60g wireless gaming mouse with HERO 2 sensor and 95-hour battery life.',
    imageUrl: 'https://placehold.co/400x300/e63946/ffffff?text=Superlight+2+MC',
    currentPrice: 129.99,
    originalPrice: 159.99,
    store: 'Micro Center',
    category: 'mouse',
    url: 'https://www.microcenter.com/product/logitech-g-pro-x-superlight-2',
    rating: 4.8,
    stock: 30,
  },
];

const gogProducts = [
  {
    name: 'The Witcher 3: Wild Hunt - Complete Edition',
    description: 'Award-winning open-world RPG with all DLC included. Next-gen update with ray tracing and improved performance.',
    imageUrl: 'https://placehold.co/400x300/6c5ce7/ffffff?text=Witcher+3+GOG',
    currentPrice: 9.99,
    originalPrice: 49.99,
    store: 'GOG',
    category: 'games',
    url: 'https://www.gog.com/en/game/the_witcher_3_wild_hunt_game_of_the_year_edition',
    rating: 4.9,
    stock: 999,
  },
  {
    name: 'Cyberpunk 2077: Ultimate Edition',
    description: 'Open-world action RPG set in Night City with Phantom Liberty expansion and all updates included.',
    imageUrl: 'https://placehold.co/400x300/6c5ce7/ffffff?text=Cyberpunk+GOG',
    currentPrice: 29.99,
    originalPrice: 59.99,
    store: 'GOG',
    category: 'games',
    url: 'https://www.gog.com/en/game/cyberpunk_2077_ultimate_edition',
    rating: 4.5,
    stock: 999,
  },
  {
    name: 'Diablo + Hellfire',
    description: 'Classic action RPG with Hellfire expansion. DRM-free, updated for modern systems with quality of life improvements.',
    imageUrl: 'https://placehold.co/400x300/6c5ce7/ffffff?text=Diablo+GOG',
    currentPrice: 4.99,
    originalPrice: 9.99,
    store: 'GOG',
    category: 'games',
    url: 'https://www.gog.com/en/game/diablo',
    rating: 4.7,
    stock: 999,
  },
  {
    name: 'System Shock Enhanced Edition',
    description: 'Enhanced re-release of the groundbreaking immersive sim. Updated controls, resolution support, and modding tools.',
    imageUrl: 'https://placehold.co/400x300/6c5ce7/ffffff?text=System+Shock+GOG',
    currentPrice: 3.99,
    originalPrice: 9.99,
    store: 'GOG',
    category: 'games',
    url: 'https://www.gog.com/en/game/system_shock_enhanced_edition',
    rating: 4.4,
    stock: 999,
  },
  {
    name: 'Baldur\'s Gate: Enhanced Edition',
    description: 'Classic D&D RPG remastered with updated visuals, new characters, and cross-platform multiplayer.',
    imageUrl: 'https://placehold.co/400x300/6c5ce7/ffffff?text=BG+Enhanced+GOG',
    currentPrice: 7.99,
    originalPrice: 19.99,
    store: 'GOG',
    category: 'games',
    url: 'https://www.gog.com/en/game/baldurs_gate_enhanced_edition',
    rating: 4.6,
    stock: 999,
  },
  {
    name: 'Planescape: Torment Enhanced Edition',
    description: 'Narrative-driven RPG enhanced with updated UI, higher resolutions, and new content. A cult classic.',
    imageUrl: 'https://placehold.co/400x300/6c5ce7/ffffff?text=Planescape+GOG',
    currentPrice: 5.99,
    originalPrice: 14.99,
    store: 'GOG',
    category: 'games',
    url: 'https://www.gog.com/en/game/planescape_torment_enhanced_edition',
    rating: 4.8,
    stock: 999,
  },
  {
    name: 'Star Wars: Knights of the Old Republic',
    description: 'Legendary BioWare RPG set in the Star Wars universe. Choose your path as Jedi or Sith.',
    imageUrl: 'https://placehold.co/400x300/6c5ce7/ffffff?text=KOTOR+GOG',
    currentPrice: 4.99,
    originalPrice: 9.99,
    store: 'GOG',
    category: 'games',
    url: 'https://www.gog.com/en/game/star_wars_knights_of_the_old_republic',
    rating: 4.8,
    stock: 999,
  },
  {
    name: 'Fallout: New Vegas Ultimate Edition',
    description: 'Open-world post-apocalyptic RPG with all DLC. Explore the Mojave Wasteland in this beloved entry.',
    imageUrl: 'https://placehold.co/400x300/6c5ce7/ffffff?text=FNV+GOG',
    currentPrice: 9.99,
    originalPrice: 19.99,
    store: 'GOG',
    category: 'games',
    url: 'https://www.gog.com/en/game/fallout_new_vegas_ultimate_edition',
    rating: 4.7,
    stock: 999,
  },
];

const gameStopProducts = [
  {
    name: 'PlayStation 5 DualSense Wireless Controller - Midnight Black',
    description: 'Wireless PS5 controller with haptic feedback, adaptive triggers, built-in microphone, and USB-C charging.',
    imageUrl: 'https://placehold.co/400x300/6c5ce7/ffffff?text=DualSense+GS',
    currentPrice: 59.99,
    originalPrice: 74.99,
    store: 'GameStop',
    category: 'console',
    url: 'https://www.gamestop.com/ps5-dualsense-controller-midnight-black',
    rating: 4.7,
    stock: 40,
  },
  {
    name: 'Xbox Series X Wireless Controller - Carbon Black',
    description: 'Wireless Xbox controller with textured grip, hybrid D-pad, share button, and USB-C connectivity.',
    imageUrl: 'https://placehold.co/400x300/6c5ce7/ffffff?text=Xbox+Controller+GS',
    currentPrice: 49.99,
    originalPrice: 64.99,
    store: 'GameStop',
    category: 'console',
    url: 'https://www.gamestop.com/xbox-series-x-controller-carbon-black',
    rating: 4.6,
    stock: 45,
  },
  {
    name: 'The Legend of Zelda: Tears of the Kingdom',
    description: 'Open-world adventure for Nintendo Switch. Explore the vast skies and mysterious lands of Hyrule.',
    imageUrl: 'https://placehold.co/400x300/6c5ce7/ffffff?text=Zelda+TOTK+GS',
    currentPrice: 49.99,
    originalPrice: 69.99,
    store: 'GameStop',
    category: 'games',
    url: 'https://www.gamestop.com/zelda-tears-of-the-kingdom',
    rating: 4.9,
    stock: 30,
  },
  {
    name: 'God of War Ragnarök',
    description: 'Epic action-adventure for PS5. Kratos and Atreus journey through the Nine Realms facing Norse gods.',
    imageUrl: 'https://placehold.co/400x300/6c5ce7/ffffff?text=GoW+Ragnarok+GS',
    currentPrice: 39.99,
    originalPrice: 69.99,
    store: 'GameStop',
    category: 'games',
    url: 'https://www.gamestop.com/god-of-war-ragnarok-ps5',
    rating: 4.8,
    stock: 25,
  },
  {
    name: 'Spider-Man 2 PS5',
    description: 'Marvel action-adventure for PS5. Play as both Peter Parker and Miles Morales in an epic story.',
    imageUrl: 'https://placehold.co/400x300/6c5ce7/ffffff?text=Spider-Man+2+GS',
    currentPrice: 44.99,
    originalPrice: 69.99,
    store: 'GameStop',
    category: 'games',
    url: 'https://www.gamestop.com/spider-man-2-ps5',
    rating: 4.7,
    stock: 28,
  },
  {
    name: 'PS5 Media Remote',
    description: 'Dedicated media remote for PS5 with dedicated streaming app buttons and intuitive navigation.',
    imageUrl: 'https://placehold.co/400x300/6c5ce7/ffffff?text=PS5+Remote+GS',
    currentPrice: 24.99,
    originalPrice: 29.99,
    store: 'GameStop',
    category: 'console',
    url: 'https://www.gamestop.com/ps5-media-remote',
    rating: 4.3,
    stock: 50,
  },
  {
    name: 'Xbox Game Pass Ultimate 3-Month Subscription',
    description: '3-month Xbox Game Pass Ultimate membership with access to hundreds of games, EA Play, and cloud gaming.',
    imageUrl: 'https://placehold.co/400x300/6c5ce7/ffffff?text=Game+Pass+GS',
    currentPrice: 39.99,
    originalPrice: 49.99,
    store: 'GameStop',
    category: 'games',
    url: 'https://www.gamestop.com/xbox-game-pass-ultimate-3-month',
    rating: 4.8,
    stock: 999,
  },
  {
    name: 'Nintendo Switch Pro Controller',
    description: 'Premium wireless controller for Nintendo Switch with traditional layout, NFC, and motion controls.',
    imageUrl: 'https://placehold.co/400x300/6c5ce7/ffffff?text=Switch+Pro+GS',
    currentPrice: 54.99,
    originalPrice: 69.99,
    store: 'GameStop',
    category: 'console',
    url: 'https://www.gamestop.com/nintendo-switch-pro-controller',
    rating: 4.6,
    stock: 35,
  },
];

const steelSeriesProducts = [
  {
    name: 'SteelSeries Apex Pro TKL Wireless (2023)',
    description: 'Wireless TKL mechanical keyboard with OmniPoint 2.0 adjustable switches, OLED display, and 40-hour battery.',
    imageUrl: 'https://placehold.co/400x300/ff6b35/ffffff?text=Apex+Pro+TKL+Wireless',
    currentPrice: 219.99,
    originalPrice: 269.99,
    store: 'SteelSeries',
    category: 'keyboard',
    url: 'https://steelseries.com/gaming-keyboards/apex-pro-tkl-wireless-2023',
    rating: 4.7,
    stock: 12,
  },
  {
    name: 'SteelSeries Arctis Nova Pro Wireless',
    description: 'Premium wireless gaming headset with active noise cancellation, Infinity Power System, and Hi-Res audio.',
    imageUrl: 'https://placehold.co/400x300/ff6b35/ffffff?text=Arctis+Nova+Pro',
    currentPrice: 299.99,
    originalPrice: 349.99,
    store: 'SteelSeries',
    category: 'headset',
    url: 'https://steelseries.com/gaming-headsets/arctis-nova-pro-wireless',
    rating: 4.8,
    stock: 10,
  },
  {
    name: 'SteelSeries Aerox 3 Wireless (2022)',
    description: 'Ultra-light 68g wireless gaming mouse with TrueMove Air sensor, AquaBarrier, and 370-hour battery.',
    imageUrl: 'https://placehold.co/400x300/ff6b35/ffffff?text=Aerox+3+Wireless',
    currentPrice: 79.99,
    originalPrice: 99.99,
    store: 'SteelSeries',
    category: 'mouse',
    url: 'https://steelseries.com/gaming-mice/aerox-3-wireless-2022',
    rating: 4.5,
    stock: 25,
  },
  {
    name: 'SteelSeries QcK Heavy XXL Mousepad',
    description: 'Extra-large 900x400mm gaming mousepad with thick 6mm rubber base, micro-woven cloth surface.',
    imageUrl: 'https://placehold.co/400x300/ff6b35/ffffff?text=QcK+Heavy+XXL',
    currentPrice: 29.99,
    originalPrice: 39.99,
    store: 'SteelSeries',
    category: 'mouse',
    url: 'https://steelseries.com/gaming-mousepads/qck-heavy-xxl',
    rating: 4.6,
    stock: 40,
  },
  {
    name: 'SteelSeries Arctis Nova 1',
    description: 'Wired gaming headset with 40mm neodymium drivers, ClearCast Gen 2 mic, and ComfortMAX system.',
    imageUrl: 'https://placehold.co/400x300/ff6b35/ffffff?text=Arctis+Nova+1',
    currentPrice: 49.99,
    originalPrice: 59.99,
    store: 'SteelSeries',
    category: 'headset',
    url: 'https://steelseries.com/gaming-headsets/arctis-nova-1',
    rating: 4.4,
    stock: 30,
  },
  {
    name: 'SteelSeries Apex 9 Mini',
    description: '60% mechanical keyboard with OptiPoint optical switches, per-key RGB, and PBT keycaps.',
    imageUrl: 'https://placehold.co/400x300/ff6b35/ffffff?text=Apex+9+Mini',
    currentPrice: 99.99,
    originalPrice: 119.99,
    store: 'SteelSeries',
    category: 'keyboard',
    url: 'https://steelseries.com/gaming-keyboards/apex-9-mini',
    rating: 4.3,
    stock: 18,
  },
  {
    name: 'SteelSeries Rival 3 Wireless',
    description: 'Wireless gaming mouse with TrueMove Air sensor, 400+ hour battery, and ultra-durable 60M click switches.',
    imageUrl: 'https://placehold.co/400x300/ff6b35/ffffff?text=Rival+3+Wireless',
    currentPrice: 39.99,
    originalPrice: 49.99,
    store: 'SteelSeries',
    category: 'mouse',
    url: 'https://steelseries.com/gaming-mice/rival-3-wireless',
    rating: 4.3,
    stock: 35,
  },
  {
    name: 'SteelSeries Arctis 1 Wireless',
    description: 'Wireless gaming headset with 2.4GHz USB-C dongle, 40mm drivers, detachable ClearCast mic, and 20-hour battery.',
    imageUrl: 'https://placehold.co/400x300/ff6b35/ffffff?text=Arctis+1+Wireless',
    currentPrice: 79.99,
    originalPrice: 99.99,
    store: 'SteelSeries',
    category: 'headset',
    url: 'https://steelseries.com/gaming-headsets/arctis-1-wireless',
    rating: 4.4,
    stock: 22,
  },
];

const walmartProducts = [
  {
    name: 'PlayStation 5 Slim Digital Edition',
    description: 'PS5 Slim Digital Edition with ultra-fast SSD, DualSense controller, and access to exclusive PS5 games.',
    imageUrl: 'https://placehold.co/400x300/0071ce/ffffff?text=PS5+Digital+WM',
    currentPrice: 399.99,
    originalPrice: 449.99,
    store: 'Walmart',
    category: 'console',
    url: 'https://www.walmart.com/ip/ps5-slim-digital-edition',
    rating: 4.7,
    stock: 20,
  },
  {
    name: 'Xbox Series S 512GB',
    description: 'Compact all-digital gaming console with 512GB SSD, 1440p gaming, Quick Resume, and Game Pass support.',
    imageUrl: 'https://placehold.co/400x300/0071ce/ffffff?text=Xbox+Series+S+WM',
    currentPrice: 249.99,
    originalPrice: 299.99,
    store: 'Walmart',
    category: 'console',
    url: 'https://www.walmart.com/ip/xbox-series-s-512gb',
    rating: 4.5,
    stock: 30,
  },
  {
    name: 'Meta Quest 3 128GB',
    description: 'Next-gen VR headset with full-color mixed reality, Snapdragon XR2 Gen 2, and 128GB storage.',
    imageUrl: 'https://placehold.co/400x300/0071ce/ffffff?text=Quest+3+WM',
    currentPrice: 399.99,
    originalPrice: 499.99,
    store: 'Walmart',
    category: 'console',
    url: 'https://www.walmart.com/ip/meta-quest-3-128gb',
    rating: 4.6,
    stock: 15,
  },
  {
    name: 'HyperX CloudX Stinger Core Wireless Xbox',
    description: 'Wireless Xbox-licensed headset with 7.1 surround sound, 17-hour battery, and memory foam ear cushions.',
    imageUrl: 'https://placehold.co/400x300/0071ce/ffffff?text=CloudX+WM',
    currentPrice: 69.99,
    originalPrice: 89.99,
    store: 'Walmart',
    category: 'headset',
    url: 'https://www.walmart.com/ip/hyperx-cloudx-stinger-core-wireless',
    rating: 4.3,
    stock: 25,
  },
  {
    name: 'Onikuma K17 Gaming Headset',
    description: 'Wired gaming headset with 50mm drivers, LED RGB lighting, noise-canceling mic, and multi-platform support.',
    imageUrl: 'https://placehold.co/400x300/0071ce/ffffff?text=Onikuma+K17+WM',
    currentPrice: 19.99,
    originalPrice: 29.99,
    store: 'Walmart',
    category: 'headset',
    url: 'https://www.walmart.com/ip/onikuma-k17-gaming-headset',
    rating: 4.2,
    stock: 50,
  },
  {
    name: 'Redragon S101 Gaming Combo',
    description: 'Gaming keyboard and mouse combo with RGB backlighting, 104 keys, 3200 DPI mouse, and anti-ghosting.',
    imageUrl: 'https://placehold.co/400x300/0071ce/ffffff?text=Redragon+S101+WM',
    currentPrice: 29.99,
    originalPrice: 39.99,
    store: 'Walmart',
    category: 'keyboard',
    url: 'https://www.walmart.com/ip/redragon-s101-gaming-combo',
    rating: 4.4,
    stock: 60,
  },
  {
    name: 'Sceptre 27" Curved Gaming Monitor 165Hz',
    description: '27-inch FHD 165Hz curved gaming monitor with AMD FreeSync, 1ms response, and built-in speakers.',
    imageUrl: 'https://placehold.co/400x300/0071ce/ffffff?text=Sceptre+27+WM',
    currentPrice: 149.99,
    originalPrice: 199.99,
    store: 'Walmart',
    category: 'monitor',
    url: 'https://www.walmart.com/ip/sceptre-27-curved-gaming-monitor',
    rating: 4.3,
    stock: 22,
  },
  {
    name: 'PowerA Enhanced Wireless Xbox Controller',
    description: 'Wireless Xbox controller with mappable back paddles, 30-hour battery, and 3.5mm audio jack.',
    imageUrl: 'https://placehold.co/400x300/0071ce/ffffff?text=PowerA+Xbox+WM',
    currentPrice: 39.99,
    originalPrice: 49.99,
    store: 'Walmart',
    category: 'console',
    url: 'https://www.walmart.com/ip/powera-enhanced-wireless-xbox-controller',
    rating: 4.3,
    stock: 35,
  },
];

const lenovoProducts = [
  {
    name: 'Lenovo Legion Pro 7i Gen 9',
    description: '16-inch WQXGA 240Hz gaming laptop with Intel Core i9-14900HX, NVIDIA RTX 4080, 32GB DDR5, 1TB SSD.',
    imageUrl: 'https://placehold.co/400x300/e2231a/ffffff?text=Legion+Pro+7i',
    currentPrice: 2199.99,
    originalPrice: 2599.99,
    store: 'Lenovo',
    category: 'laptop',
    url: 'https://www.lenovo.com/us/en/p/legion-pro-7i-gen-9',
    rating: 4.7,
    stock: 6,
  },
  {
    name: 'Lenovo Legion 5i Gen 9',
    description: '16-inch WQXGA 165Hz gaming laptop with Intel i7-14700HX, NVIDIA RTX 4060, 16GB DDR5, 512GB SSD.',
    imageUrl: 'https://placehold.co/400x300/e2231a/ffffff?text=Legion+5i',
    currentPrice: 1199.99,
    originalPrice: 1449.99,
    store: 'Lenovo',
    category: 'laptop',
    url: 'https://www.lenovo.com/us/en/p/legion-5i-gen-9',
    rating: 4.5,
    stock: 12,
  },
  {
    name: 'Lenovo Legion Tower 7i Gaming Desktop',
    description: 'Gaming desktop with Intel i9-14900KF, NVIDIA RTX 4080 Super, 32GB DDR5, 2TB SSD, and liquid cooling.',
    imageUrl: 'https://placehold.co/400x300/e2231a/ffffff?text=Legion+Tower+7i',
    currentPrice: 2499.99,
    originalPrice: 2999.99,
    store: 'Lenovo',
    category: 'laptop',
    url: 'https://www.lenovo.com/us/en/p/legion-tower-7i-gaming-desktop',
    rating: 4.6,
    stock: 4,
  },
  {
    name: 'Lenovo Legion R27i-30 27" Gaming Monitor',
    description: '27-inch QHD 180Hz IPS gaming monitor with AMD FreeSync Premium, 99% sRGB, and 0.5ms response time.',
    imageUrl: 'https://placehold.co/400x300/e2231a/ffffff?text=Legion+R27i',
    currentPrice: 249.99,
    originalPrice: 319.99,
    store: 'Lenovo',
    category: 'monitor',
    url: 'https://www.lenovo.com/us/en/p/legion-r27i-30',
    rating: 4.4,
    stock: 18,
  },
  {
    name: 'Lenovo Legion M500 RGB Wireless Gaming Mouse',
    description: 'Wireless gaming mouse with 19K DPI sensor, 5 programmable buttons, RGB lighting, and 60-hour battery.',
    imageUrl: 'https://placehold.co/400x300/e2231a/ffffff?text=Legion+M500',
    currentPrice: 49.99,
    originalPrice: 59.99,
    store: 'Lenovo',
    category: 'mouse',
    url: 'https://www.lenovo.com/us/en/p/legion-m500-wireless-mouse',
    rating: 4.3,
    stock: 25,
  },
  {
    name: 'Lenovo Legion K500 RGB Mechanical Keyboard',
    description: 'Full-size mechanical keyboard with Kailh Red switches, per-key RGB, and aircraft-grade aluminum frame.',
    imageUrl: 'https://placehold.co/400x300/e2231a/ffffff?text=Legion+K500',
    currentPrice: 69.99,
    originalPrice: 89.99,
    store: 'Lenovo',
    category: 'keyboard',
    url: 'https://www.lenovo.com/us/en/p/legion-k500-rgb-keyboard',
    rating: 4.3,
    stock: 20,
  },
  {
    name: 'Lenovo LOQ 15 Gaming Laptop',
    description: '15.6-inch FHD 144Hz gaming laptop with AMD Ryzen 7 7840HS, NVIDIA RTX 4060, 16GB DDR5, 512GB SSD.',
    imageUrl: 'https://placehold.co/400x300/e2231a/ffffff?text=LOQ+15',
    currentPrice: 899.99,
    originalPrice: 1099.99,
    store: 'Lenovo',
    category: 'laptop',
    url: 'https://www.lenovo.com/us/en/p/loq-15-gaming-laptop',
    rating: 4.4,
    stock: 15,
  },
  {
    name: 'Lenovo Legion H500 Pro 7.1 Gaming Headset',
    description: 'Wired 7.1 surround sound headset with 50mm drivers, retractable mic, and memory foam ear cushions.',
    imageUrl: 'https://placehold.co/400x300/e2231a/ffffff?text=Legion+H500',
    currentPrice: 59.99,
    originalPrice: 79.99,
    store: 'Lenovo',
    category: 'headset',
    url: 'https://www.lenovo.com/us/en/p/legion-h500-pro-headset',
    rating: 4.3,
    stock: 22,
  },
];

const hyperxProducts = [
  {
    name: 'HyperX Cloud III Wireless',
    description: 'Wireless gaming headset with DTS Spatial Audio, 53mm drivers, 120-hour battery, and memory foam.',
    imageUrl: 'https://placehold.co/400x300/e60012/ffffff?text=Cloud+III+Wireless',
    currentPrice: 129.99,
    originalPrice: 159.99,
    store: 'HyperX',
    category: 'headset',
    url: 'https://hyperx.com/products/cloud-iii-wireless',
    rating: 4.6,
    stock: 18,
  },
  {
    name: 'HyperX Cloud Alpha Wireless',
    description: 'Wireless gaming headset with dual-chamber audio, 300-hour battery, and DTS Headphone:X spatial audio.',
    imageUrl: 'https://placehold.co/400x300/e60012/ffffff?text=Cloud+Alpha+Wireless',
    currentPrice: 149.99,
    originalPrice: 199.99,
    store: 'HyperX',
    category: 'headset',
    url: 'https://hyperx.com/products/cloud-alpha-wireless',
    rating: 4.7,
    stock: 12,
  },
  {
    name: 'HyperX Alloy Origins 60',
    description: 'Ultra-compact 60% mechanical keyboard with HyperX Red switches, PBT keycaps, and RGB lighting.',
    imageUrl: 'https://placehold.co/400x300/e60012/ffffff?text=Alloy+Origins+60',
    currentPrice: 79.99,
    originalPrice: 99.99,
    store: 'HyperX',
    category: 'keyboard',
    url: 'https://hyperx.com/products/alloy-origins-60',
    rating: 4.5,
    stock: 20,
  },
  {
    name: 'HyperX Pulsefire Surge RGB',
    description: 'Wired gaming mouse with 16K DPI sensor, 6 programmable buttons, 360-degree RGB, and Omron switches.',
    imageUrl: 'https://placehold.co/400x300/e60012/ffffff?text=Pulsefire+Surge',
    currentPrice: 39.99,
    originalPrice: 49.99,
    store: 'HyperX',
    category: 'mouse',
    url: 'https://hyperx.com/products/pulsefire-surge-rgb',
    rating: 4.4,
    stock: 30,
  },
  {
    name: 'HyperX CloudX Stinger Core Xbox',
    description: 'Xbox-licensed wired headset with 7.1 surround sound, lightweight design, and swivel-to-mute mic.',
    imageUrl: 'https://placehold.co/400x300/e60012/ffffff?text=CloudX+Stinger',
    currentPrice: 39.99,
    originalPrice: 49.99,
    store: 'HyperX',
    category: 'headset',
    url: 'https://hyperx.com/products/cloudx-stinger-core-xbox',
    rating: 4.3,
    stock: 25,
  },
  {
    name: 'HyperX Fury S Pro XL Mousepad',
    description: 'Extra-large 420x900mm gaming mousepad with anti-fray stitching, dense cloth surface, and non-slip base.',
    imageUrl: 'https://placehold.co/400x300/e60012/ffffff?text=Fury+S+Pro+XL',
    currentPrice: 24.99,
    originalPrice: 34.99,
    store: 'HyperX',
    category: 'mouse',
    url: 'https://hyperx.com/products/fury-s-pro-xl',
    rating: 4.5,
    stock: 40,
  },
  {
    name: 'HyperX SoloCast USB Microphone',
    description: 'USB condenser microphone with tap-to-mute, cardioid pattern, adjustable stand, and plug-n-play setup.',
    imageUrl: 'https://placehold.co/400x300/e60012/ffffff?text=SoloCast',
    currentPrice: 39.99,
    originalPrice: 59.99,
    store: 'HyperX',
    category: 'component',
    url: 'https://hyperx.com/products/solocast-usb-microphone',
    rating: 4.4,
    stock: 22,
  },
  {
    name: 'HyperX QuadCast S RGB USB Microphone',
    description: 'Premium USB condenser mic with RGB lighting, tap-to-mute, 4 polar patterns, anti-vibration mount.',
    imageUrl: 'https://placehold.co/400x300/e60012/ffffff?text=QuadCast+S',
    currentPrice: 119.99,
    originalPrice: 159.99,
    store: 'HyperX',
    category: 'component',
    url: 'https://hyperx.com/products/quadcast-s-rgb',
    rating: 4.7,
    stock: 15,
  },
];

module.exports = {
  gpu, keyboards, mice, monitors, laptops, consoles, mercadolibre,
  dellProducts, microCenterProducts, gogProducts, gameStopProducts,
  steelSeriesProducts, walmartProducts, lenovoProducts, hyperxProducts,
};
